# -*- coding: utf-8 -*-
"""
/***************************************************************************
                                 A QGIS plugin
 This plugin creates label connector (line from centroid to the label)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-13
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Oslandia
        email                : infos@oslandia.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os


def populateComboBox(comboBox):
    comboBox.clear()
    stylesDir = os.path.join(os.path.dirname(__file__), "labelStyles")
    if os.path.isdir(stylesDir):
        for f in os.listdir(stylesDir):
            styleFile = os.path.join(stylesDir, f)
            if os.path.isfile(styleFile):
                comboBox.addItem(f, styleFile)
    else:
        os.mkdir(stylesDir)
